# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
# Mybatis配置
mybatis:
    mapperLocations: classpath:mappers/**/*.xml
    type-aliases-package: com.smms.pojo.po
#通用Mapper
mapper:
  mappers: com.smms.util.MyMapper
  not-empty: false
  identity: MYSQL
#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#lockback配置
logging:
  file: D://smms/smms.log



